name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Run Tests and Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
        MIX_ENV: test
      run: mix coveralls.post --branch "${GITHUB_REF}" --name "GH ${GITHUB_WORKFLOW}" --committer "${GITHUB_ACTOR}" --sha "${GITHUB_SHA}"
